# Generated by Django 6.0.3 on 2026-03-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('streetlight', 'Streetlight'), ('water_leaks', 'Water Leaks'), ('waste_sanitation', 'Waste & Sanitation'), ('roads_potholes', 'Roads & Potholes'), ('environment_health', 'Environment & Public Health'), ('parks_biodiversity', 'Parks, Trees & Biodiversity'), ('electricity', 'Electricity')], max_length=30)),
                ('sub_issue', models.CharField(blank=True, choices=[('light_not_working', 'Light Not Working'), ('light_fitting', 'Light Fitting Missing/Stolen'), ('cable_theft', 'Cable Theft From Pole'), ('pole_damage', 'Pole Damage'), ('light_on', 'Light On During Day'), ('water_pipe', 'Water Pipe Damaged/Leaking'), ('water_meter', 'Water Meter Damage'), ('water_outage', 'Localised Water Outage'), ('sewerage_leak', 'Sewerage Leak'), ('illegal_dumping', 'Illegal Dumping'), ('storm_drain', 'Storm Drain Blocked'), ('missed_collection', 'Missed Collection Day'), ('overflowing_bin', 'Overflowing Bin'), ('pothole', 'Pothole'), ('sinkhole', 'Sinkhole'), ('road_markings', 'Faded Road Markings'), ('traffic_sign', 'Traffic Sign Damaged'), ('pavement_damaged', 'Pavement Damaged'), ('hazardous_waste', 'Hazardous Waste'), ('water_pollution', 'Water Pollution'), ('sewage_outfalls', 'Sewage Into Rivers'), ('oil_spill', 'Oil/Fuel Spill'), ('asbestos_exposure', 'Asbestos Exposure'), ('illegal_trading', 'Illegal Trading'), ('trees', 'Fallen Tree/Dangerous Branches'), ('maintenance', 'Overgrown Verge/Park Maintenance'), ('tree_felling', 'Illegal Tree Felling'), ('playground', 'Playground Equipment Broken'), ('electricity_outage', 'Localised Electricity Outage'), ('illegal_connection', 'Illegal Connection Suspected'), ('substation_fault', 'Substation Fault Suspected'), ('exposed_cable', 'Exposed Live Cable'), ('traffic_lights', 'Traffic Lights Broken')], max_length=30)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('municipality', models.CharField(blank=True, choices=[('COJ', 'City of Johannesburg'), ('COT', 'City of Tshwane'), ('EKU', 'Ekurhuleni'), ('CoCT', 'City of Cape Town'), ('ETH', 'eThekwini'), ('NMB', 'Nelson Mandela Bay'), ('MAN', 'Mangaung'), ('BUF', 'Buffalo City'), ('OTHER', 'Other')], max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('issue_has_worsened', 'Issue Has Worsened'), ('issue_is_ongoing', 'Issue Is Ongoing'), ('issue_fixed', 'Issue Fixed'), ('escalated_to_municipality', 'Escalated To Municipality'), ('scheduled_for_service', 'Scheduled For Service'), ('work_in_progress', 'Work In Progress')], default='open', max_length=30)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20)),
                ('reference_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
