# Generated by Django 6.0.3 on 2026-03-29 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NearbySearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5')])),
                ('resolved', models.CharField(choices=[('yes', 'Fully Resolved'), ('partial', 'Partially Resolved'), ('no', 'Still Not Fixed'), ('worse', 'Made Worse')], max_length=10)),
                ('comment', models.TextField(blank=True)),
                ('reporter_name', models.CharField(blank=True, max_length=100)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='Reporting.report')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_status', models.CharField(choices=[('open', 'Open'), ('issue_has_worsened', 'Issue Has Worsened'), ('issue_is_ongoing', 'Issue Is Ongoing'), ('issue_fixed', 'Issue Fixed'), ('escalated_to_municipality', 'Escalated To Municipality'), ('scheduled_for_service', 'Scheduled For Service'), ('work_in_progress', 'Work In Progress')], max_length=30)),
                ('note', models.TextField(blank=True)),
                ('updated_by', models.CharField(default='System', max_length=100)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_updates', to='Reporting.report')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
